# Generated by Django 2.1 on 2021-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telzir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eo', models.FloatField(max_length=1)),
                ('ed', models.FloatField(max_length=1)),
                ('min', models.FloatField()),
                ('ofm', models.FloatField(max_length=1)),
            ],
        ),
    ]
